#! /bin/bash
set -eo pipefail
IFS="$(printf '\n\t')"
#cd "$(dirname "${BASH_SOURCE[0]}")"

CHROME_DIR="$HOME/Library/Application Support/Google/Chrome"

TEMP_DIR="$(mktemp -d)"

cd "$TEMP_DIR"

profiles=$(cd "$CHROME_DIR" && ls -d Default 'Profile '*)
for profile in $profiles; do
	cp "$CHROME_DIR/$profile/Web Data" "$TEMP_DIR/$profile"
	sqlite3 "$TEMP_DIR/$profile" <<- EOF
		.mode insert
		.output '$profile.data'
		SELECT short_name, keyword, url, favicon_url
			FROM keywords
			WHERE keyword NOT LIKE '%.%'
		;
	EOF
	sed 's/table/keyword/' "$profile.data" | sort > "$profile.data.sorted"
	rm "$profile" "$profile.data"
done

for profile1 in $profiles; do
	for profile2 in $profiles; do
		if [ "$profile1" == "$profile2" ]; then
			continue
		fi

		set +e
		diff --changed-group-format='%>' --unchanged-group-format='' "$profile1.data.sorted" "$profile2.data.sorted" > "$profile2-for-$profile1.sql"
		set -e
	done
done
rm *.sorted

echo "Finished"
echo "Close Chrome and then cd to the below directory and run the sql scripts"
echo "cd $TEMP_DIR"
