#! /bin/bash
set -e
set -o pipefail
IFS="$(printf '\n\t')"
case "$1" in
    '')
        echo Please specify folder
        exit 1
        ;;
esac
set -u

mkdir -p previews

ls "$1" | while IFS='' read -r file || [[ "$file" ]]; do
    echo ffmpeg -ss 00:01:30 -t 00:00:30 -i "$1/$file" "previews/$file"
done
